### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by migueldelmazo** [mariaozamiz/number-guessing-game#1]
Really cool job @mariaozamiz !!!

Here you have some tips to improve the exercise:

### JavaScript: basic

- [x] Extract the feedback painter to a function.

### JavaScript: advanced

- [x] Move the feedback logic to a function and execute it on each click.
- [x] Move you counter logic into a function and execute it on each click.
- [x] You are writing many times "trackEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'trackEl'?
- [x] Use `ev.preventDefault()` to prevent page reload.
- [x] Move `ev.preventDefault()` to first line of the function.

### HTML

- [x] Add form
- [x] Use placeholder.

### Steps to finish the game (for those far from the solution)

You are close to the exercise solution, but here you have a steps guide to complete it anyway ;)

1. Save a reference to DOM elements in variables.
2. Generate the random number and save it to a variable.
3. Init counter of trials to 0.
4. Define a function that executes when the user clicks on the button, that

- increments the counter and paints its value in the HTML.
- collect the value of the HTML input and compare it with the random number.
  - if they are equal, draw a 'You Win' message.
  - if it's lower, draw a 'Too short' message.
  - if it's higher, draw a 'Too long' message.

5. Assign a listener to the button click to execute the previous function.

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

> Do not close this issue until your teacher asks you to

**Comment by mariaozamiz** [comment]
Hola Miguel,

Gracias por el feedback. He corregido el ejercicio pero tengo dudas sobre los puntos 1 y 3:

- El punto 1, ¿se refiere a crear el randomNumber al hacer click en el botón? En mi ejercicio se activa esa función al cargar la página, no sé si esto es una mala práctica o también valdría.

- El punto 3, ¿está pidiendo declarar variables para cada pista para luego introducirlas en la función? Me he fijado en el ejercicio de Kayla, ¿es esto lo que se pide?
https://github.com/Adalab/modulo-2-evaluacion-intermedia-kaylacrane/blob/master/js/main.js

No sé si mi problema es con el inglés, con JS o ambos 😄 
¡Gracias y buen finde!

**Comment by migueldelmazo** [comment]
Hola María,

yo tampoco me estoy enterando. El apartado Steps to finish the game es por si no has sabido hacer el ejercicio, te damos unas pequeñas pistas. Y el apartado Further challenges es por si te aburres.

Mañana lo comentamos, pídeme soporte en el pair programming.

Chao!
